[theme]
#Primary accent color for interactive element.
primaryColor = 'green'

# Background color for the main content area.
backgroundColor = '#00132B'

#Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = '#0063B8'

#Color used for almost all text.
textColor = '#FFF'

# font family for all text in the app, except code blocks. One of 'sans serif', 'serif', or 'monospace'.
# Default: 'sans serif'
font = 'sans serif'